#!/usr/bin/env python3
"""Deux constructions indépendantes, les mêmes octets — preuve de candidat.

Un manuel qu'on ne peut pas refabriquer à l'identique n'est pas livrable : ce
que l'imprimeur reçoit doit être ce que le dépôt décrit, aujourd'hui et dans
six mois. La reproductibilité se prouve donc en construisant DEUX fois et en
comparant les octets, pas en faisant confiance au pipeline.

Ce que ce module constate, et rien de plus : deux constructions successives des
mêmes sources de manuel donnent des PDF byte-identiques. Le statut reste
`CANDIDATE_REPRODUCIBLE` -- il ne devient une preuve de RELEASE qu'une fois les
verdicts humains clos et le contenu figé, et si les sources finales produisent
alors ces mêmes empreintes, la preuve se réutilise par égalité d'empreinte.

Une subtilité qui rend le constat plus fort qu'il n'en a l'air : les deux
constructions n'ont pas été lancées au même commit. Entre elles, des artefacts
d'audit ont été livrés -- des propositions de barème, des dossiers de revue.
Aucune SOURCE du manuel n'a bougé, et l'identité de trailer, qui suit ces
sources, est restée la même. Les octets aussi.

Métriques bloquantes : `VARIANTS_COMPARED`, `VARIANTS_DIFFERING`.
"""

from __future__ import annotations

import argparse
import hashlib
import json
import subprocess
import sys
from pathlib import Path
from typing import Any

sys.path.insert(0, str(Path(__file__).resolve().parent))

from manual_source_surface import ROOT  # noqa: E402

JSON_TARGET = ROOT / "audit/1SPE_CANDIDATE_REPRODUCIBILITY.json"
MD_TARGET = ROOT / "audit/1SPE_CANDIDATE_REPRODUCIBILITY.md"
GENERATED_BY = "scripts/build_1spe_candidate_reproducibility.py"

BUILD = ROOT / "Mathematiques/manuel-maths/build/MANUEL_1SPE"
VARIANTS = ("eleve", "professeur")
STATUS = "CANDIDATE_REPRODUCIBLE"


class ReproducibilityError(RuntimeError):
    """Une preuve manque : la comparaison ne peut pas être faite."""


def _digest(path: Path) -> str:
    return "sha256:" + hashlib.sha256(path.read_bytes()).hexdigest()


def _page_count(path: Path) -> int:
    try:
        import fitz  # noqa: PLC0415
    except ModuleNotFoundError as error:  # pragma: no cover - dépendance
        raise ReproducibilityError("PyMuPDF (fitz) est requis") from error
    with fitz.open(path) as document:
        return document.page_count


def build_evidence(runs: dict[str, dict[str, str]]) -> dict[str, Any]:
    """`runs` : pour chaque variante, l'empreinte observée à la construction A."""

    variants: list[dict[str, Any]] = []
    for variant in VARIANTS:
        pdf = BUILD / f"MANUEL_1SPE_{variant}.pdf"
        if not pdf.is_file():
            raise ReproducibilityError(f"PDF absent : {pdf}")
        if variant not in runs:
            raise ReproducibilityError(f"aucune empreinte A pour {variant}")
        after = _digest(pdf)
        before = runs[variant]["pdf_sha256"]
        variants.append(
            {
                "variant": variant,
                "pdf_path": str(pdf.relative_to(ROOT)),
                "source_sha_a": runs[variant]["source_sha"],
                "source_sha_b": runs[variant]["source_sha_b"],
                "pdf_sha256_a": before,
                "pdf_sha256_b": after,
                "identical": before == after,
                "page_count": _page_count(pdf),
            }
        )
    differing = [row for row in variants if not row["identical"]]
    return {
        "artifact_type": "1spe_candidate_reproducibility",
        "schema_version": 1,
        "generated_by": GENERATED_BY,
        "status": STATUS,
        "approves_nothing": True,
        "why_this_is_not_release_evidence": (
            "Le statut reste CANDIDATE_REPRODUCIBLE tant que les verdicts "
            "humains ne sont pas clos et que le contenu n'est pas figé. Si les "
            "sources finales produisent ces mêmes empreintes, cette preuve se "
            "réutilise par égalité d'empreinte ; sinon un A/B final est dû."
        ),
        "the_two_runs_were_not_at_the_same_commit": (
            "Entre les deux constructions, seuls des artefacts d'audit ont été "
            "livrés. Aucune source du manuel n'a bougé, et l'identité de "
            "trailer -- qui suit ces sources -- est restée la même. Les octets "
            "aussi : c'est un constat plus fort qu'une reproduction au même "
            "commit."
        ),
        "variants": variants,
        "summary": {
            "VARIANTS_COMPARED": len(variants),
            "VARIANTS_DIFFERING": len(differing),
            "IDENTICAL": len(variants) - len(differing),
            "PAGE_COUNTS": {row["variant"]: row["page_count"] for row in variants},
        },
    }


def render_markdown(payload: dict[str, Any]) -> str:
    lines = [
        "# Reproductibilité des candidats — 1SPE",
        "",
        f"<!-- generated by {GENERATED_BY} -->",
        "",
        f"Statut : `{payload['status']}`.",
        "",
        f"> {payload['why_this_is_not_release_evidence']}",
        "",
        f"> {payload['the_two_runs_were_not_at_the_same_commit']}",
        "",
        "## Métriques",
        "",
        "| Métrique | Valeur |",
        "|---|---:|",
    ]
    for name, value in payload["summary"].items():
        lines.append(f"| `{name}` | {value} |")
    lines += [
        "",
        "## Comparaison",
        "",
        "| Variante | Pages | SHA source A | SHA source B | PDF A | PDF B | A == B |",
        "|---|---:|---|---|---|---|---|",
    ]
    for row in payload["variants"]:
        lines.append(
            f"| {row['variant']} | {row['page_count']} | "
            f"`{row['source_sha_a'][:10]}` | `{row['source_sha_b'][:10]}` | "
            f"`{row['pdf_sha256_a'][7:19]}` | `{row['pdf_sha256_b'][7:19]}` | "
            f"{'oui' if row['identical'] else '**NON**'} |"
        )
    return "\n".join(lines) + "\n"


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--runs", type=Path, required=True, help="JSON des runs A")
    parser.add_argument("--check", action="store_true", help="ne rien écrire")
    arguments = parser.parse_args(argv)

    try:
        runs = json.loads(arguments.runs.read_text(encoding="utf-8"))
        payload = build_evidence(runs)
    except (ReproducibilityError, OSError, json.JSONDecodeError) as error:
        print(f"1SPE-CANDIDATE-REPRODUCIBILITY-ERROR: {error}", file=sys.stderr)
        return 2

    if not arguments.check:
        JSON_TARGET.write_text(
            json.dumps(payload, ensure_ascii=False, indent=2, sort_keys=True) + "\n",
            encoding="utf-8",
        )
        MD_TARGET.write_text(render_markdown(payload), encoding="utf-8")
        print(f"écrit {JSON_TARGET.name} et {MD_TARGET.name}")
    for name, value in payload["summary"].items():
        print(f"{name}={value}")
    return 1 if payload["summary"]["VARIANTS_DIFFERING"] else 0


if __name__ == "__main__":
    raise SystemExit(main())
